apiVersion: v1
kind: Template
metadata:
  name: mattermost-push-proxy
  creationTimestamp: null
objects:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: "mattermost-push-proxy-config"
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: "1Gi"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      service: mattermost-push-proxy
    name: mattermost-push-proxy
  spec:
    replicas: 1
    selector:
      service: mattermost-push-proxy
    strategy:
     resources:
        requests:
            cpu: 20m
            memory: 500Mi
        limits:
            cpu: 200m
            memory: 500Mi
    rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
    type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: mattermost-push-proxy
      spec:
        containers:
        - image: registry.centos.org/mattermost/mattermost-push-proxy:3.10.0
          imagePullPolicy: Always
          name: mattermost-push-proxy
          ports:
          - containerPort: 8066
            protocol: TCP
          env:
            - name: GOOGLERNAPIKEY
              valueFrom:
                secretKeyRef:
                  name: mattermost-push-proxy-config
                  key: googleapikey
            - name: GOOGLEAPIKEY
              valueFrom:
                 secretKeyRef:
                  name: mattermost-push-proxy-config
                  key: googleapikey
            - name: APPLEPUSHCERT
              valueFrom:
                secretKeyRef:
                  name: mattermost-push-proxy-config
                  key: applepushcert
            - name: APPLEPUSHRNCERT
              valueFrom:
                secretKeyRef:
                  name: mattermost-push-proxy-config
                  key: applepushrncert
            - name: APPLEPUSHPASS
              valueFrom:
                secretKeyRef:
                  name: mattermost-push-proxy-config
                  key: applepushpass
            - name: APPLEPUSHRNPASS
              valueFrom:
                secretKeyRef:
                  name: mattermost-push-proxy-config
                  key: applepushrnpass
          volumeMounts:
            - name: config
              mountPath: /opt/mattermost-push-proxy/config
        volumes:
        - name: config
          persistentVolumeClaim:
            claimName: mattermost-push-proxy-config
        resources: {}
        terminationMessagePath: /dev/termination-log
        readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8066
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
        livenessProbe:
            httpGet:
              path: /
              port: 8066
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: mattermost-push-proxy
    name: mattermost-push-proxy
  spec:
    ports:
    - name: 8066-tcp
      port: 8066
      protocol: TCP
      targetPort: 8066
    selector:
      service: mattermost-push-proxy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      service: mattermost-push-proxy
    name: mattermost-push-proxy
  spec:
    host: ''
    port:
      targetPort: 8066-tcp
    to:
      kind: Service
      name: mattermost-push-proxy
      weight: 100
    wildcardPolicy: None
  status: {}
parameters:
- name: IMAGE_TAG
  value: latest
